config/routes.rb
Rails.application.routes.draw do
  resources :coparts
  resources :filtercoparts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/copart.rb
class Copart < ApplicationRecord
end

app/models/filtercopart.rb
class Filtercopart < ApplicationRecord
    
  before_save :default_values

	def default_values
	  self.year = '1900' if self.year.nil?
	  self.to_year = '2100' if self.to_year.nil?
	  self.odometer = 0 if self.odometer.nil?
	  self.to_odometer = 9999999 if self.to_odometer.nil?
	end


	def correct_year(year_p)
          year_from = self.year ||= 1900
          year_to = self.to_year ||= 2100
          year_csv = year_p ||= year_from
          year_csv = year_csv.to_i 

	  if year_from.to_i <= year_csv && year_to.to_i >= year_csv
	    then true
	  else
	    false
	  end
	end


	def correct_odo(odo_p)
          odo_from = self.odometer ||= 0
          odo_to = self.to_odometer ||= 9999999
          odo_csv = odo_p ||= odo_from
          odo_csv = odo_csv.to_i
	  if odo_from <= odo_csv && odo_to >= odo_csv
	    then true
	  else
	    false
	  end
	end
end

app/models/filterlink.rb
class Filterlink < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coparts_controller.rb
class CopartsController < ApplicationController
  before_action :set_copart, only: [:show, :edit, :update, :destroy]

  # GET /coparts
  # GET /coparts.json
  def index
    @coparts = Copart.all
  end

  # GET /coparts/1
  # GET /coparts/1.json
  def show
  end

  # GET /coparts/new
  def new
    @copart = Copart.new
  end

  # GET /coparts/1/edit
  def edit
  end

  # POST /coparts
  # POST /coparts.json
  def create
    @copart = Copart.new(copart_params)

    respond_to do |format|
      if @copart.save
        format.html { redirect_to @copart, notice: 'Copart was successfully created.' }
        format.json { render :show, status: :created, location: @copart }
      else
        format.html { render :new }
        format.json { render json: @copart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coparts/1
  # PATCH/PUT /coparts/1.json
  def update
    respond_to do |format|
      if @copart.update(copart_params)
        format.html { redirect_to @copart, notice: 'Copart was successfully updated.' }
        format.json { render :show, status: :ok, location: @copart }
      else
        format.html { render :edit }
        format.json { render json: @copart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coparts/1
  # DELETE /coparts/1.json
  def destroy
    @copart.destroy
    respond_to do |format|
      format.html { redirect_to coparts_url, notice: 'Copart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_copart
      @copart = Copart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def copart_params
      params.require(:copart).permit(:record_status, :lot_n, :row_hash, :lot_img_fld)
    end
end

app/controllers/filtercoparts_controller.rb
class FiltercopartsController < ApplicationController
  before_action :set_filtercopart, only: [:show, :edit, :update, :destroy]

  # GET /filtercoparts
  # GET /filtercoparts.json
  def index
    @filtercoparts = Filtercopart.all
  end

  # GET /filtercoparts/1
  # GET /filtercoparts/1.json
  def show
  end

  # GET /filtercoparts/new
  def new
    @filtercopart = Filtercopart.new
  end

  # GET /filtercoparts/1/edit
  def edit
  end

  # POST /filtercoparts
  # POST /filtercoparts.json
  def create
    @filtercopart = Filtercopart.new(filtercopart_params)

    respond_to do |format|
      if @filtercopart.save
        format.html { redirect_to @filtercopart, notice: 'Copart Filter was successfully created.' }
        format.json { render :show, status: :created, location: @filtercopart }
      else
        format.html { render :new }
        format.json { render json: @filtercopart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filtercoparts/1
  # PATCH/PUT /filtercoparts/1.json
  def update
    respond_to do |format|
      if @filtercopart.update(filtercopart_params)
        format.html { redirect_to @filtercopart, notice: 'Copart Filter was successfully updated.' }
        format.json { render :show, status: :ok, location: @filtercopart }
      else
        format.html { render :edit }
        format.json { render json: @filtercopart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filtercoparts/1
  # DELETE /filtercoparts/1.json
  def destroy
    @filtercopart.destroy
    respond_to do |format|
      format.html { redirect_to filtercoparts_url, notice: 'Copart Filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filtercopart
      @filtercopart = Filtercopart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filtercopart_params
      params.require(:filtercopart).permit(:record_status, :vechile_type, :year, 
        :make, :model_group, :model_detail, :damage_description, :lot_cond, 
        :odometer, :engine, :drive, :transmission, :fuel_type, :runs_drives, :location_city, 
        :buy_it_now_price, :color, :sale_date , :to_year, :to_odometer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coparts_helper.rb
module CopartsHelper
end

app/helpers/filtercoparts_helper.rb
module FiltercopartsHelper
end

app/views/coparts/_form.html.erb
<%= form_with(model: copart, local: true) do |form| %>
  <% if copart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(copart.errors.count, "error") %> prohibited this copart from being saved:</h2>

      <ul>
      <% copart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :record_status %>
    <%= form.text_field :record_status, id: :copart_record_status %>
  </div>

  <div class="field">
    <%= form.label :lot_n %>
    <%= form.text_field :lot_n, id: :copart_lot_n %>
  </div>

  <div class="field">
    <%= form.label :row_hash %>
    <%= form.text_area :row_hash, id: :copart_row_hash %>
  </div>

  <div class="field">
    <%= form.label :lot_img_fld %>
    <%= form.text_field :lot_img_fld, id: :copart_lot_img_fld %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coparts/edit.html.erb
<h1>Editing Copart</h1>

<%= render 'form', copart: @copart %>

<%= link_to 'Show', @copart %> |
<%= link_to 'Back', coparts_path %>

app/views/coparts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coparts</h1>

<table>
  <thead>
    <tr>
      <th>Record status</th>
      <th>Lot n</th>
      <th>Row hash</th>
      <th>Lot img fld</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coparts.each do |copart| %>
      <tr>
        <td><%= copart.record_status %></td>
        <td><%= copart.lot_n %></td>
        <td><%= copart.row_hash %></td>
        <td><%= copart.lot_img_fld %></td>
        <td><%= link_to 'Show', copart %></td>
        <td><%= link_to 'Edit', edit_copart_path(copart) %></td>
        <td><%= link_to 'Destroy', copart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Copart', new_copart_path %>

app/views/coparts/new.html.erb
<h1>New Copart</h1>

<%= render 'form', copart: @copart %>

<%= link_to 'Back', coparts_path %>

app/views/coparts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Record status:</strong>
  <%= @copart.record_status %>
</p>

<p>
  <strong>Lot n:</strong>
  <%= @copart.lot_n %>
</p>

<p>
  <strong>Row hash:</strong>
  <%= @copart.row_hash %>
</p>

<p>
  <strong>Lot img fld:</strong>
  <%= @copart.lot_img_fld %>
</p>

<%= link_to 'Edit', edit_copart_path(@copart) %> |
<%= link_to 'Back', coparts_path %>

app/views/filtercoparts/_form.html.erb
<%= form_with(model: filtercopart, local: true) do |form| %>
  <% if filtercopart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(filtercopart.errors.count, "error") %> prohibited this filtercopart from being saved:</h2>

      <ul>
      <% filtercopart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :record_status %>
    <%= form.select :record_status, ['A', 'D']%>
  </div>

    <div class="field">
    <%= form.label :sale_date %>
    <%= form.text_field :sale_date, id: :filtercopart_sale_date %>
  </div>

  <div class="field">
    <%= form.label :vechile_type %>
    <%= form.text_field :vechile_type, id: :filtercopart_vechile_type %>
  </div>

  <div class="field">
    <%= form.label :year_from %>
    <%= form.text_field :year, id: :filtercopart_year %>
  </div>

  <div class="field">
    <%= form.label :year_to %>
    <%= form.text_field :to_year, id: :filtercopart_year %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make, id: :filtercopart_make %>
  </div>

  <div class="field">
    <%= form.label :model_group %>
    <%= form.text_field :model_group, id: :filtercopart_model_group %>
  </div>

  <div class="field">
    <%= form.label :model_detail %>
    <%= form.text_field :model_detail, id: :filtercopart_model_detail %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :filtercopart_color %>
  </div>  

  <div class="field">
    <%= form.label :damage_description %>
    <%= form.text_field :damage_description, id: :filtercopart_damage_description %>
  </div>

  <div class="field">
    <%= form.label :lot_cond %>
    <%= form.text_field :lot_cond, id: :filtercopart_lot_cond %>
  </div>

  <div class="field">
    <%= form.label :odometer_from %>
    <%= form.number_field :odometer, id: :filtercopart_odometer %>
  </div>

  <div class="field">
    <%= form.label :odometer_to %>
    <%= form.number_field :to_odometer, id: :filtercopart_to_odometer %>
  </div>

  <div class="field">
    <%= form.label :engine %>
    <%= form.text_field :engine, id: :filtercopart_engine %>
  </div>

  <div class="field">
    <%= form.label :drive %>
    <%= form.text_field :drive, id: :filtercopart_drive %>
  </div>

  <div class="field">
    <%= form.label :transmission %>
    <%= form.text_field :transmission, id: :filtercopart_transmission %>
  </div>

  <div class="field">
    <%= form.label :fuel_type %>
    <%= form.text_field :fuel_type, id: :filtercopart_fuel_type %>
  </div>

  <div class="field">
    <%= form.label :runs_drives %>
    <%= form.text_field :runs_drives, id: :filtercopart_runs_drives %>
  </div>

  <div class="field">
    <%= form.label :location_city %>
    <%= form.text_field :location_city, id: :filtercopart_location_city %>
  </div>



  <div class="actions">
    <%= form.submit "დამახსოვრება" %>
  </div>
<% end %>

app/views/filtercoparts/edit.html.erb
<h1>ფილტრის რედაქტირება</h1>

<%= render 'form', filtercopart: @filtercopart %>

<%= link_to 'Show', @filtercopart %> |
<%= link_to 'Back', filtercoparts_path %>

app/views/filtercoparts/index.html.erb
<head>
<style>
  table#t01 tr#t02 {
      border: 1px solid black;
        border-collapse: collapse;    
      color: black;
      padding: 5px;
      font-size: 15px;

      margin: auto;
      width: 60%;
  }


th#t03 {
      border: 1px solid black;
        border-collapse: collapse;    
      color: black;
      padding: 5px;
      font-size: 15px;

      margin: auto;
      width: auto;

      background-color: #6a99c8;
  }

th#t07 {
      border: 1px solid black;
        border-collapse: collapse;    
      color: black;
      padding: 5px;
      font-size: 15px;

      margin: auto;
      width: auto;

      background-color: #6a99c8;
  }



#t04
  {border: 1px solid black;
     border-collapse: collapse; 
     color: black;
   }

#t05
  {border: 1px solid black;
     border-collapse: collapse; 
     color: black;
   padding: 5px;     
   }


table#t01 tr:nth-child(even) {
      background-color: #eee;
    }

table#t01 tr:nth-child(odd) {
      background-color:#fff;
       }

</style>
</head>

<body>

<div align="center">

<p id="notice"><%= notice %></p>

<h1>არსებული ფილტრები</h1>

<table id="t01">
  <thead>
    <tr id="t02">
      <th id="t03">Record status</th>
      <th id="t03">Vechile type</th>
      <th id="t03">Year_from</th>
      <th id="t03">Year_to</th>
      <th id="t03">Make</th>
      <th id="t03">Model group</th>
      <th id="t03">Model detail</th>
      <th id="t03">Color</th>      
      <th id="t03">Damage description</th>
      <th id="t03">Lot cond</th>
      <th id="t03">Odometer from</th>
      <th id="t03">Odometer to</th>
      <th id="t03">Engine</th>
      <th id="t03">Drive</th>
      <th id="t03">Transmission</th>
      <th id="t03">Fuel type</th>
      <th id="t03">Runs drives</th>
      <th id="t03">Location city</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filtercoparts.each do |filtercopart| %>
      <tr id="t04">
        <td id="t05"><%= filtercopart.record_status %></td>
        <td id="t05"><%= filtercopart.vechile_type %></td>
        <td id="t05"><%= filtercopart.year %></td>
        <td id="t05"><%= filtercopart.to_year %></td> 
        <td id="t05"><%= filtercopart.make %></td>
        <td id="t05"><%= filtercopart.model_group %></td>
        <td id="t05"><%= filtercopart.model_detail %></td>
        <td id="t05"><%= filtercopart.color %></td>
        <td id="t05"><%= filtercopart.damage_description %></td>
        <td id="t05"><%= filtercopart.lot_cond %></td>
        <td id="t05"><%= filtercopart.odometer %></td>
        <td id="t05"><%= filtercopart.to_odometer %></td>
        <td id="t05"><%= filtercopart.engine %></td>
        <td id="t05"><%= filtercopart.drive %></td>
        <td id="t05"><%= filtercopart.transmission %></td>
        <td id="t05"><%= filtercopart.fuel_type %></td>
        <td id="t05"><%= filtercopart.runs_drives %></td>
        <td id="t05"><%= filtercopart.location_city %></td>

        <td id="t05"><%= link_to 'ჩვენება', filtercopart %></td>
        <td id="t05"><%= link_to 'რედაქტირება', edit_filtercopart_path(filtercopart) %></td>
        <td id="t05"><%= link_to 'წაშლა', filtercopart_path(filtercopart), method: :delete, data: { confirm: 'ნამდვილად გსურთ წაშლა?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ახალი ფილტრის დამატება', new_filtercopart_path %>

</div>

app/views/filtercoparts/new.html.erb
<h1>ახალი ფილტრის დამატება</h1>

<%= render 'form', filtercopart: @filtercopart %>

<%= link_to 'Back', filtercoparts_path %>

app/views/filtercoparts/show.html.erb
<head>
<style>

#td-left
  {
   border-right: 5px solid #6a99c8;
   border-bottom: 1px  solid #6a99c8;
   border-collapse: collapse; 
   padding-right: 15px; 
   padding-bottom: 4px; 
   padding-top: 4px;      
   font-size: 15px;  
   text-align: right;  
   }

#td-right
  {
   border-bottom: 1px solid #6a99c8;
   padding-left: 15px;  
   font-size: 15px; 
   text-align: left; 
   padding-bottom: 4px; 
   padding-top: 4px;     
  }

table#t01 tr:nth-child(even) {
      background-color: #fff;
    }

table#t01 tr:nth-child(odd) {
      background-color:#eee;
       }


</style>
</head>

<body>

<p id="notice"><%= notice %></p>

<table align="center" id="t01">
  <tr>
    <td id="td-left"> 
      <%= link_to 'მთავარ გვერდზე დაბრუნება',  filtercoparts_path, method: :get, class: "btn btn-xs btn-success"  %>
    </td> 
    <td id="td-right">
      <%= link_to 'ჩანაწერის რედაქტირება',  edit_filtercopart_path(@filtercopart) , class: "btn btn-xs btn-primary" %>
    </td>
  </tr> 
  <tr>
    <td id="td-left"></td> 
    <td id="td-right"></td>
  </tr> 

  <tr>
    <td id="td-left">Record status:</td> 
    <td id="td-right"><%= @filtercopart.record_status %></td>
  </tr>

  <tr>
    <td id="td-left">sale_date:</td> 
    <td id="td-right"><%= @filtercopart.sale_date %></td>
  </tr>

  <tr>
    <td id="td-left">Vechile type:</td> 
    <td id="td-right"><%= @filtercopart.vechile_type %></td>
  </tr>

  <tr>
    <td id="td-left">Year_from:</td> 
    <td id="td-right"><%= @filtercopart.year %></td>
  </tr>
  <tr>
    <td id="td-left">Year_to:</td> 
    <td id="td-right"><%= @filtercopart.to_year %></td>
  </tr>
  <tr>
    <td id="td-left">Make:</td> 
    <td id="td-right"> <%= @filtercopart.make %></td>
  </tr>

  <tr>
    <td id="td-left">Model group:</td> 
    <td id="td-right"> <%= @filtercopart.model_group %></td>
  </tr>

  <tr>
    <td id="td-left">Model detail:</td> 
    <td id="td-right"> <%= @filtercopart.model_detail %></td>
  </tr>

  <tr>
    <td id="td-left">Color:</td> 
    <td id="td-right"> <%= @filtercopart.color %></td>
  </tr>

  <tr>
    <td id="td-left">Damage description:</td> 
    <td id="td-right"><%= @filtercopart.damage_description %></td>
  </tr>

  <tr>
    <td id="td-left">Lot cond:</td> 
    <td id="td-right">  <%= @filtercopart.lot_cond %></td>
  </tr>

  <tr>
    <td id="td-left">Odometer_from:</td> 
    <td id="td-right">  <%= @filtercopart.odometer %></td>
  </tr>
  <tr>
    <td id="td-left">Odometer_to:</td> 
    <td id="td-right">  <%= @filtercopart.to_odometer %></td>
  </tr>


  <tr>
    <td id="td-left">Engine:</td> 
    <td id="td-right">   <%= @filtercopart.engine %></td>
  </tr>

  <tr>
    <td id="td-left">Drive:</td> 
    <td id="td-right">   <%= @filtercopart.drive %></td>
  </tr>

  <tr>
    <td id="td-left">Transmission:</td> 
    <td id="td-right">    <%= @filtercopart.transmission %></td>
  </tr>

  <tr>
    <td id="td-left">Fuel type:</td> 
    <td id="td-right">      <%= @filtercopart.fuel_type %></td>
  </tr>

  <tr>
    <td id="td-left">Runs drives:</td> 
    <td id="td-right">  <%= @filtercopart.runs_drives %></td>
  </tr>

  <tr>
    <td id="td-left">Location city:</td> 
    <td id="td-right">  <%= @filtercopart.location_city %></td>
  </tr>



</table>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skyscraper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>